import { StyleSheet } from 'react-native';

const styles = StyleSheet.create({
    container: {
        flex: 1,
        alignItems: 'center', 
        justifyContent: 'flex-start',
        padding: 30, 
        paddingTop: 50,
    },
    image: { flex: 1 },
    logoImg: {
        resizeMode: 'contain',
        width: 150, 
        height: 100,
    },
    title: {
        alignSelf: 'flex-start',
        fontWeight: 'bold',
        fontSize: 25,
        color: 'black',
        marginTop: 20,
        marginBottom: 20,
    },
    card: {
        width: '100%',
        backgroundColor: 'white',
        padding: 20,
        borderRadius: 10,
        marginBottom: 20,
        shadowColor: "#000",
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.1,
        shadowRadius: 4,
        elevation: 3,
    },
    questionText: {
        fontSize: 16,
        fontWeight: 'bold',
        marginBottom: 15,
        color: '#333',
    },
    optionsContainer: { gap: 15 },
    radioContainer: { flexDirection: 'row', alignItems: 'center' },
    outerCircle: {
        height: 20, width: 20, borderRadius: 10,
        borderWidth: 2, borderColor: '#666',
        justifyContent: 'center', alignItems: 'center',
        marginRight: 10,
    },
    outerCircleSelected: { borderColor: '#3FA9F5' },
    innerCircle: { height: 10, width: 10, borderRadius: 5, backgroundColor: '#3FA9F5' },
    radioLabel: { fontSize: 16, color: 'black' },
    
    buttonRow: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        gap: 10,
    },
    noBtn: {
        flex: 1, height: 45,
        backgroundColor: '#ccc',
        justifyContent: 'center', alignItems: 'center',
        borderRadius: 5,
    },
    yesBtn: {
        flex: 1, height: 45,
        backgroundColor: '#3FA9F5',
        justifyContent: 'center', alignItems: 'center',
        borderRadius: 5,
    },
    noBtnText: { color: 'black', fontWeight: 'bold' },
    yesBtnText: { color: 'white', fontWeight: 'bold' },
    radioSublabel: {
        fontSize: 11,
        color: '#888',
        marginTop: 1,
    },
    nextBtn: {
        width: '100%',
        height: 50,
        backgroundColor: '#3FA9F5',
        justifyContent: 'center',
        alignItems: 'center',
        borderRadius: 8,
        marginTop: 10,
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.2,
        shadowRadius: 3,
        elevation: 5,
    },
    nextBtnText: {
        color: 'white',
        fontWeight: 'bold',
        fontSize: 16,
    },
    codeInput: {
        width: '100%',
        height: 50,
        borderWidth: 1.5,
        borderColor: '#3FA9F5',
        borderRadius: 8,
        paddingHorizontal: 15,
        fontSize: 18,
        fontWeight: 'bold',
        color: '#000',
        backgroundColor: '#fff',
        letterSpacing: 2,
    },
    backBtn: {
        flexDirection: 'row',
        alignItems: 'center',
        position: 'absolute',
        top: 50,
        left: 20,
        zIndex: 10,
    },
    backIcon: {
        width: 20,
        height: 20,
        resizeMode: 'contain',
        marginRight: 5,
    },
    backText: {
        fontSize: 16,
        fontWeight: 'bold',
        color: '#000',
    },
});

export default styles;