import { StyleSheet } from 'react-native';

const styles = StyleSheet.create({
    buttonRow: {
        flexDirection: 'row',       
        justifyContent: 'space-between', 
        width: '100%',
        marginTop: 20,
        gap: 10,                    
    },
    halfBtn: {
        flex: 1,                    
        height: 50,
        backgroundColor: '#3FA9F5',
        justifyContent: 'center',
        alignItems: 'center',
        borderRadius: 5,
        shadowColor: "#000",
        shadowOffset: {
            width: 0,
            height: 2,
        },
        shadowOpacity: 0.25,
        shadowRadius: 3.84,
        elevation: 5,
    },
    saveText: {
        color: 'white',
        fontWeight: 'bold',
        fontSize: 14, 
    },

    backBtn: {
        position: 'absolute',
        top: 50, 
        left: 20,
        zIndex: 10,
        flexDirection: 'row',
        alignItems: 'center',
        padding: 5,
    },
    backIcon: {
        width: 20, 
        height: 20,
        resizeMode: 'contain',
        marginRight: 5,
        tintColor: '#3FA9F5',
    },
    backText: {
        fontSize: 16,
        fontWeight: 'bold',
        color: '#3FA9F5',
    },
    container: {
        flex: 1,
        alignItems: 'center', 
        justifyContent: 'flex-start',
        padding: 30, 
        paddingTop: 30,
    },
    logoImg: {
        resizeMode: 'contain',
        width: 150, 
        height: 100,
        marginTop: 30
    },
    title: {
        alignSelf: 'flex-start',
        fontWeight: 'bold',
        fontSize: 25,
        color: 'black',
        marginTop: 10,
        marginBottom: 5,
    },
    nameIn: {
        height: 40,
        width: '100%',
        marginVertical: 5,
        borderWidth: 1,
        borderColor: '#ccc',
        borderRadius: 5,
        padding: 10,
        backgroundColor: 'white',
    },
    rowWrapper: {
        flexDirection: 'row', 
        width: '100%',
        justifyContent: 'space-between',
        alignItems: 'center',
        marginVertical: 5,
        gap: 10, 
    },
    addressInput: {
        flex: 2, 
        height: 50, 
        borderWidth: 1,
        borderColor: '#ccc',
        borderRadius: 5,
        padding: 10,
        backgroundColor: 'white',
    },
    pickerContainer: {
        flex: 1.5, 
        height: 50, 
        borderWidth: 1,
        borderColor: '#ccc',
        borderRadius: 5,
        backgroundColor: 'white',
        justifyContent: 'center', 
        overflow: 'hidden', 
    },
    picker: {
        width: '100%',
        height: 50,
        color: 'black',
    },
    dateInputHalf: {
        flex: 1, 
        height: 50,
        borderWidth: 1,
        borderColor: '#ccc',
        borderRadius: 5,
        padding: 10,
        justifyContent: 'center',
        backgroundColor: 'white',
    },
    medRecContainer: {
      width: '100%',
      marginTop: 10,
      marginBottom: 10,
    },
    medRecLabel: {
      fontWeight: 'bold',
      fontSize: 12,
      marginBottom: 5, 
      textAlign: 'left',
    },
    medRecButtonsRow: {
      flexDirection: 'row', 
      alignItems: 'center',
      justifyContent: 'flex-start', 
      gap: 20, 
    },
    genderGroup: {
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'flex-end', 
    },
    genderLabel: {
      fontWeight: 'bold',
      fontSize: 14,
    },
    dateText: {
        fontSize: 14, 
        color: 'black',
    },
    radioContainer: {
        flexDirection: 'row',
        alignItems: 'center',
        marginLeft: 10, 
    },
    outerCircle: {
        height: 18,
        width: 18,
        borderRadius: 9,
        borderWidth: 2,
        borderColor: '#666',
        justifyContent: 'center',
        alignItems: 'center',
        marginRight: 4,
        backgroundColor: 'white',
    },
    outerCircleSelected: {
        borderColor: '#3FA9F5',
    },
    innerCircle: {
        height: 9,
        width: 9,
        borderRadius: 4.5,
        backgroundColor: '#3FA9F5',
    },
    radioLabel: {
        fontSize: 14,
        color: 'black',
    },
    image: {
      flex: 1,
    },
});

export default styles;