import { StyleSheet } from 'react-native';

const styles = StyleSheet.create({
    container: {
        flex: 1,
        alignItems: 'center',
        justifyContent: 'center',
    },
    subLabel: {
        fontSize: 10,
        fontWeight: 'bold',
        color: '#ff0000', 
        width: '60%',
        marginBottom: 20,
        marginTop: -10,
        marginLeft: 20,
        textAlign: 'left', 
    },
    register: {
       flexDirection: 'row',
       marginTop: 10,
    },
    registerBtn: {
       fontWeight: 'bold',
       color: '#3FA9F5',
       fontSize: 16,
       marginLeft: 5, 
       shadowColor: "#000",
        shadowOffset: {
            width: 0,
            height: 2,
        },
        shadowOpacity: 0.25,
        shadowRadius: 4,
        elevation: 5,
    },
    logoImg:{
      resizeMode:'contain',
      width: 200,
      height: 180,
      marginTop: 10,
      marginBottom: 5,
    },
    backBtn: {
      flexDirection: 'row',
      alignItems: 'center',
      position: 'absolute',
      top: 50,
      left: 20,
      zIndex: 10,
    },
    backIcon: {
      width: 20,
      height: 20,
      resizeMode: 'contain',
      marginRight: 5,
    },
    backText: {
      fontSize: 16,
      fontWeight: 'bold',
      color: '#000',
    },
    image: {
      flex: 1,
    },
    loginBtn: {
      width: '50%',
      height: 50,
      backgroundColor: '#3FA9F5',
      justifyContent: 'center',
      alignItems: 'center',
      borderRadius: 5,
      shadowColor: "#000",
        shadowOffset: {
            width: 0,
            height: 2,
        },
        shadowOpacity: 0.25,
        shadowRadius: 4,
        elevation: 5,
    },
    loginText: {
      color: 'white',
      fontWeight: 'bold',
      fontSize: 16,
    },
    title: {
        fontWeight: 'bold',
        fontSize: 35,
        color: '#3FA9F5',
        marginBottom: 20,
        textShadowColor: 'rgba(0, 0, 0, 0.75)', 
        textShadowOffset: { width: 0, height: 2 }, 
        textShadowRadius: 2, 
    },
    inputWrapper: {
      flexDirection: 'row', 
      alignItems: 'center', 
      width: '60%', 
      height: 50, 
      borderRadius: 10,
      paddingHorizontal: 15, 
      marginBottom: 15, 
      backgroundColor: '#FFFFFF',
      shadowColor: '#000',
      shadowOffset: { width: 0, height: 2 },
      shadowOpacity: 1, 
      shadowRadius: 4, 
      elevation: 3
    },
    icon: {
      width: 24, 
      height: 24,
      marginRight: 10, 
      tintColor: '#2F7FB8', 
      resizeMode: 'contain'
    },
    input: {
      flex: 1, 
      fontWeight: 'bold',
      fontSize: 16,
      height: '100%', 
      color: '#000',
    },
    profilePicContainer: {
        width: 100,
        height: 100,
        borderRadius: 50,
        backgroundColor: 'rgba(255,255,255,0.8)',
        borderWidth: 2,
        borderColor: '#3FA9F5',
        justifyContent: 'center',
        alignItems: 'center',
        marginBottom: 20,
        overflow: 'hidden',
    },
    profilePlaceholder: {
        justifyContent: 'center',
        alignItems: 'center',
    },
    placeholderIcon: {
        width: 30,
        height: 30,
        tintColor: '#aaa',
        marginBottom: 5,
    },
    uploadPicText: {
        fontSize: 10,
        color: '#666',
        fontWeight: 'bold',
    },
    profileImage: {
        width: '100%',
        height: '100%',
        resizeMode: 'cover',
    },
    eyeBtn: {
        paddingHorizontal: 5,
        justifyContent: 'center',
        alignItems: 'center',
    },
    eyeText: {
        fontSize: 12,
        fontWeight: 'bold',
        color: '#2F7FB8',
    },
});

export default styles;